FROM mcr.microsoft.com/vscode/devcontainers/cpp

RUN apt update
RUN apt upgrade -y
RUN apt install -y libasound2-dev \
    libcurl4-openssl-dev \
    libfontconfig1-dev \
    libgtk-3-dev \
    libfreetype6-dev \
    libwebkit2gtk-4.0-dev \
    mesa-utils \
    mingw-w64
